php:
  image: php:7.4-cli
  container_name: meu-php
  ports:
    - "80:80"
  volumes:
    - ./:/var/www
  links:
    - mysql  

composer:
  image: php:7.4-cli
  container_name: meu-php
  ports:
    - "80:80"
  volumes:
    - ./:/var/www
  links:
    - mysql  

  
mysql:
  image: mysql:latest
  container_name: meu-mysql
  ports:
    - "3307:3306"
  volumes:
    - ./database:/usr/sbin/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=648270

